<!--Modellare la struttura di una tabella per memorizzare tutti i dati riguardanti delle auto usate messe in vendita da un concessionario.
Create un file txt, dove indicate il nome della tabella, le colonne con tipi di dato ed eventuali attributi.
Ricordatevi che l'esercitazione pomeridiana sarà non oggi, ma domani :occhiolino:
Buon lavoro!-->


CARS

ID   - INT - PRIMARY KEY - NOTNULL - AUTOINCREMENT - UNIQUE
DEALER NAME - VARCHAR(60) - NOTNULL
DEALER ADRESS - VARCHAR(60) - NOTNULL
MAKE - VARCHAR(15) - NOTNULL
MODEL - VARCHAR(15) - NOTNULL
PLATE NUMBER - VARCHAR(7) - NOTNULL - UNIQUE            
ENGINE SIZE - MEDIUMINT - NOTNULL - MEDIUMINT
ENGINE POWER - MEDIUMINT - NOTNULL - TINYINT
GEARBOX - VARCHAR(15) - NOTNULL
WEIGTH - DECIMAL(4,4) - NULL
LENGTH - DECIMAL(4,4) - NULL
HEITGH - DECIMAL(4,4) - NULL
DOORS - TINYINT - NOTNULL 
SEATS - TINYINT - NOTNULL
BODY TYPE - VARCHAR(10) - NULL
MILEAGE - MEDIUMINT - NOTNULL
YEAR - YEAR - MEDIUMINT - NOTNULL
FUEL TYPE - VARCHAR(20) - NOTNULL
PRICE - DECIMAL(6,4) - NOTNULL
DRIVETRAIN - VARCHAR(15) - NULL
CONSUMPTION - DECIMAL(2,2) - NULL
CO2 EMISSION - DECIMAL(2,2) - NULL
COLOR - VARCHAR(10) - NULL
SPARE WHEEL - VARCHAR(5) - NULL
SERVICE  VARCHAR(5) - NULL
SATNAV  VARCHAR(5) - NULL
AIRBAGS  VARCHAR(5) - NULL
ABS  VARCHAR(5) - NULL
ESP  VARCHAR(5) - NULL
ELECTRIC SEATS  VARCHAR(5) - NULL
KEYLESS  VARCHAR(5) - NULL
ISOFIX  VARCHAR(5) - NULL
DAB RADIO  VARCHAR(5) - NULL
LED HEADLIGHT  VARCHAR(5) - NULL
LEATHER SEATS  VARCHAR(5) - NULL



